-- drop all tables
DROP TABLE item_value IF EXISTS;

-- create new ones
CREATE TABLE item_value (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY,
   creation TIMESTAMP,
   last_update TIMESTAMP,
   update_count INTEGER,
   dashboard_id VARCHAR(255),
   item_name VARCHAR(255),
   data LONGVARCHAR
);
CREATE INDEX idx_dasboard_id_item_name ON item_value (dashboard_id,item_name,last_update);